### ISSUE TITLE
Could not parse JSON (lexical error: invalid char in json text.)

### ISSUE THREAD

**Issue by pfabreu** [rgerardi/i3status-wrapper#1]
I'm trying to get this working but I keep having this error. Could you give me an example of what the output of a custom script should be?

I have the following in my i3 config:
```
bar {
       position top
       status_command i3status | i3status-wrapper custom.sh
}
```

**Comment by rgerardi** [comment]
HI Pedro,
Make sure that `i3status` is configured to output JSON by adding this to the general section in `i3status` config file: `output_format = "i3bar"`.

The output of the custom script can be a simple line of text to be displayed like `V 0/1`, in which case `i3status-wrapper` will wrap it automatically. If you want to use addition options, such as color, your custom script can output JSON like this:

```
{"name":"playerctl","instance":"1","color":"#FF0000", "full_text":" /"}
```

Please let me know if it works.
Ricardo

**Comment by pfabreu** [comment]
Thank you, I just tried something like `echo {"name":"playerctl","instance":"1","color":"#FF0000", "full_text":" /"}` in custom.sh and I still get that error. I have set output_format = "i3bar".

**Comment by rgerardi** [comment]
Hey Pedro,
Can you send me your configuration files and the custom script so I can try to replicate on my end?
Also, which i3 and i3status versions are you using?
Thanks,
Ricardo

**Comment by pfabreu** [comment]
thanks dude, I ended up sticking to the original i3, you may close the issue
